language: c++
os:
  - linux
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"


    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - libstdc++-7-dev
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - cmake --build . --target all -- -j 4
  - bin/run_tests

