version: '3.7'

services:
  html-analysis:
    image: astaruch/html-analysis
    container_name: html-analysis
    build:
      context: ./modules/html-analysis
      target: server
      args:
        - PORT=${HTML_ANALYSIS_PORT}
    expose:
        - "${HTML_ANALYSIS_PORT}"
    ports:
        - "${HTML_ANALYSIS_PORT}:${HTML_ANALYSIS_PORT}"
    network_mode: bridge

  phishtank-updater:
    image: astaruch/phishtank-updater
    container_name: phishtank-updater
    build:
      context: ./modules/phishtank-updater
      target: cronjob
    environment:
        TYPEORM_HOST: "phishscore-db"
        TYPEORM_PORT: 5432
    env_file:
    - .env
    network_mode: bridge

  phishscore-deps:
    image: astaruch/phishscore-deps
    container_name: phishscore-deps
    build:
      context: ./modules/phishscore
      target: dependencies

  phishscore-builder:
    image: astaruch/phishscore-builder
    container_name: phishscore-builder
    build:
      context: ./modules/phishscore
      target: builder
      # https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/#the-cache-from-argument
      cache_from:
        - astaruch/phishscore-deps

  phishscore:
    image: astaruch/phishscore
    container_name: phishscore
    build:
      context: ./modules/phishscore
      target: runtime
      cache_from:
          - astaruch/phishscore-deps
          - astaruch/phishscore-builder
    environment:
        THESIS_DB_HOST: phishscore-db
    network_mode: bridge

  phishscore-db:
    image: postgres:11.2
    restart: always
    container_name: phishscore-db
    environment:
      POSTGRES_DB: ${THESIS_DB_DBNAME}
      POSTGRES_PASSWORD: ${THESIS_DB_PASSWORD}
      POSTGRES_USER: ${THESIS_DB_USER}
    expose:
      - "${THESIS_DB_PORT}"
    ports:
      - "${THESIS_DB_PORT}:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${THESIS_DB_DOCKER_VOLUME}
