version: '3.7'

services:
  thesis-db:
    image: postgres:11.2
    restart: always
    container_name: thesis-db
    environment:
      POSTGRES_DB: ${THESIS_DB_DBNAME}
      POSTGRES_PASSWORD: ${THESIS_DB_PASSWORD}
      POSTGRES_USER: ${THESIS_DB_USER}
    expose:
      - "${THESIS_DB_PORT}"
    ports:
      - "${THESIS_DB_PORT}:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    network_mode: bridge

volumes:
    db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${THESIS_DB_DOCKER_VOLUME}
