
pack:
	venv/bin/pyinstaller --clean --onefile --add-data extra_trees_model_15features.pkl:extra_trees_model_15features.pkl --distpath bin --name model-checker model.py

clean:
	rm -rf __pycache__ build bin dist *.spec 
