version: '3.7'

services:
  thesis-db:
    image: postgres:11.2
    restart: always
    container_name: thesis-db
    environment:
      POSTGRES_DB: phishing-detection
    expose:
      - "15432"
    ports:
      - "15432:5432"
    volumes:
      - /home/astaruch/Documents/code/docker-volumes/thesis-db:/var/lib/postgresql/data
    network_mode: bridge

  thesis-deps:
    image: thesis/deps
    container_name: thesis-deps
    build:
      context: .
      target: thesis-deps
      # https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/#the-cache-from-argument
      cache_from:
        - thesis/deps
        - astaruch/thesis-deps
    network_mode: bridge

  thesis-builder:
    image: thesis/builder
    container_name: thesis-builder
    build:
      context: .
      target: thesis-builder
    network_mode: bridge

  thesis-svc:
    image: thesis/runtime
    container_name: thesis-svc
    build:
      context: .
      target: thesis-svc
    network_mode: bridge
    depends_on:
      - "thesis-db"

